version: 2

jobs:
  build-job:
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
      - image: circleci/postgres:alpine
        environment:
        - POSTGRES_USER: default
        - POSTGRES_DB: default
        - POSTGRES_PASSWORD: secret
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt install -y libpq-dev postgresql-client zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install pgsql pdo pdo_pgsql
      - run: sudo composer self-update
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: php artisan migrate --env=testing --database=pgsql --force
      - run: ./vendor/bin/phpunit

  deploy-job:
    docker:
      - image: ubuntu
    working_directory: /tmp/my-project  
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git wget
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "7a:3c:2e:99:38:fe:f3:67:cb:0f:6e:e7:d6:41:13:62"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            heroku run --app $HEROKU_APP_NAME php artisan migrate --force

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
